# Generated by Django 4.1.5 on 2023-03-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wage',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default='3', verbose_name='Месяц'),
        ),
    ]
