# Generated by Django 4.1.5 on 2023-03-01 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Номер телефона начинается со знака "+" и содержить только цифры', regex='^\\+[0-9]$')], verbose_name='Телефон'),
        ),
    ]
